parameters:
    api_images.classes.loader:           "Youshido\\ImagesBundle\\Services\\Loader"
    api_images.classes.path_geherator:   "Youshido\\ImagesBundle\\Services\\PathGenerator\\DatePathGenerator"
    api_images.classes.saver:            "Youshido\\ImagesBundle\\Services\\Saver\\LocalFilesystemSaver"
    api_images.classes.path_resolver:    "Youshido\\ImagesBundle\\Services\\PathResolver\\LocalPathResolver"
    api_images.classes.resizer:          "Youshido\\ImagesBundle\\Services\\Resizer"
    api_images.classes.image_controller: "Youshido\\ImagesBundle\\Controller\\ImageController"

services:

    api_images.resizer:
        class: "%api_images.classes.resizer%"
        arguments:
            - "@api_images.saver"
            - "@api_images.path_resolver"
            - "%api_images.config.driver%"

    api_images.loader:
        public: false
        class: "%api_images.classes.loader%"
        arguments:
            - "@api_images.path_resolver"
            - "@api_images.path_geherator"
            - "@api_images.saver"

    api_images.path_geherator:
        public: false
        class: "%api_images.classes.path_geherator%"

    api_images.saver:
        public: false
        class: "%api_images.classes.saver%"

    api_images.path_resolver:
        public: false
        class: "%api_images.classes.path_resolver%"
        arguments:
            - "@router"
            - "%api_images.config.web_root%"
            - "%api_images.config.path_prefix%"
            - "%api_images.config.host%"
            - "%api_images.config.scheme%"

